In [1]:
# importing data

%pip install pandas
%pip install scikit-learn
%pip install numpy

import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
# reading data

'''
with open('AAPL.csv','r') as f:
    r = f.readlines()
    r = [r[i][:-1:].split(',') for i in range(len(r))]

    for i in range(len(r)):
        r[i][0],r[i][1] = int(r[i][0]),float(r[i][1])

X = np.array([r[i][0] for i in range(len(r))]).reshape(-1, 1)
Y = np.array([r[i][1] for i in range(len(r))]).reshape(-1, 1)
'''

import pandas as pd

# The data

from datetime import datetime

'''
# Read the CSV file
df = pd.read_csv('AAPL5Y.csv')

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Calculate the number of days since '05/22/2019' for each date
start_date = datetime.strptime('05/22/2019', '%m/%d/%Y')
df['Days'] = (df['Date'] - start_date).dt.days

# Extract the 'Close/Last' prices and remove the '$' sign
df['Close/Last'] = df['Close/Last'].str.replace('$', '').astype(float)

# Now, 'X' is the 'Days' column and 'Y' is the 'Close/Last' column
X = df['Days'].values.reshape(-1, 1)
Y = df['Close/Last'].values.reshape(-1, 1)
'''

# Read the CSV file
df = pd.read_csv('AAPL5Y.csv')

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Calculate the number of days since '05/22/2019' for each date
start_date = datetime.strptime('05/22/2019', '%m/%d/%Y')
df['Days'] = (df['Date'] - start_date).dt.days

# Extract the 'Close/Last' prices and remove the '$' sign
df['Close/Last'] = df['Close/Last'].str.replace('$', '').astype(float)

# Now, 'X' is the 'Days' column and 'Y' is the 'Close/Last' column
X = df['Days'].values.reshape(-1, 1)
Y = df['Close/Last'].values.reshape(-1, 1)

print(X)
print(Y)

[[1826]
 [1825]
 [1822]
 ...
 [   2]
 [   1]
 [   0]]
[[192.35  ]
 [191.04  ]
 [189.87  ]
 ...
 [ 44.7425]
 [ 44.915 ]
 [ 45.695 ]]


In [3]:
# Normalize the input features

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(df['Days'].values.reshape(-1, 1))
Y = df['Close/Last'].values.reshape(-1, 1)

print(X)
print()
print(Y)

[[1.00000000e+00]
 [9.99452355e-01]
 [9.97809419e-01]
 ...
 [1.09529025e-03]
 [5.47645126e-04]
 [0.00000000e+00]]

[[192.35  ]
 [191.04  ]
 [189.87  ]
 ...
 [ 44.7425]
 [ 44.915 ]
 [ 45.695 ]]


In [4]:
# importing tensorflow dependencies

%pip install tensorflow

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense

from sklearn.metrics import accuracy_score

Note: you may need to restart the kernel to use updated packages.


In [5]:
'''
# build and compile tensorflow model

model = Sequential()
model.add(Dense(units=32, activation='relu', input_dim=1))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
'''

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

# build and compile tensorflow model
model = Sequential()
model.add(Dense(units=256, activation='relu', input_dim=1))
model.add(Dense(units=512, activation='relu'))
model.add(Dense(units=256, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=1))  # Remove 'sigmoid' activation for regression

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
# model.compile(loss='mean_squared_error', optimizer='sgd')


# compile model

optimizer = Adam(learning_rate=0.0005)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [8]:
# fit model

# model.fit(X, Y, epochs=500, batch_size=40)


# fit model
early_stop = EarlyStopping(monitor='val_loss', patience=20)
# model.fit(X, Y, epochs=1000, batch_size=8, validation_split=0.2, callbacks=[early_stop])

model.fit(X, Y, epochs=8000, batch_size=4, validation_split=0.2)

Epoch 1/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 217.4604 - val_loss: 1519.8325
Epoch 2/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 209.6183 - val_loss: 1434.0963
Epoch 3/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 239.2196 - val_loss: 1374.7788
Epoch 4/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 231.0214 - val_loss: 1880.9341
Epoch 5/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 227.2338 - val_loss: 1155.9136
Epoch 6/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 229.7698 - val_loss: 2214.9192
Epoch 7/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 229.5511 - val_loss: 1512.3923
Epoch 8/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 226.9043 - val_loss: 1329.3370
Epoch 9/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 220.8901 - val_loss: 1571.0625
Epoch 10/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 213.8760 - val_loss: 1899.9634
Epoch 11/8000
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 212.57

In [9]:
# getting the test data
'''
import pandas as pd
from datetime import datetime

# Read the CSV file
ndf = pd.read_csv('AAPLTest.csv')

# Convert the 'Date' column to datetime format
ndf['Date'] = pd.to_datetime(ndf['Date'])

# Calculate the number of days since '05/22/2019' for each date
start_date = datetime.strptime('05/22/2019', '%m/%d/%Y')
ndf['Days'] = (ndf['Date'] - start_date).dt.days

# Now, 'X' is the 'Days' column
x_test = ndf['Days'].tolist()

x_test = np.array(x_test).reshape(-1, 1)

print(x_test)
'''

# getting the test data
ndf = pd.read_csv('AAPLTest.csv')
ndf['Date'] = pd.to_datetime(ndf['Date'])
ndf['Days'] = (ndf['Date'] - start_date).dt.days
x_test = scaler.transform(ndf['Days'].values.reshape(-1, 1))
y_test = ndf['Close/Last'].str.replace('$', '').astype(float).values.reshape(-1, 1)

print(x_test)
print(y_test)

[[0.99288061]
 [0.98521358]
 [0.97042716]
 [0.96276013]
 [0.932092  ]
 [0.89813801]
 [0.85049288]
 [0.80230011]
 [0.74808324]
 [0.70098576]
 [0.66374589]]
[[182.74]
 [169.02]
 [171.48]
 [173.  ]
 [188.63]
 [189.69]
 [177.23]
 [175.43]
 [153.71]
 [150.18]
 [152.37]]


In [10]:
# evaluate model

y_hat = model.predict(x_test)
print(y_hat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 301ms/step
[[181.18526]
 [176.46631]
 [171.78508]
 [173.33928]
 [188.5122 ]
 [187.3178 ]
 [180.4062 ]
 [176.39352]
 [152.99919]
 [147.2484 ]
 [153.84889]]


In [11]:
# Calculate the evaluation metrics
from sklearn.metrics import mean_squared_error, r2_score

y_true = y_test
y_pred = y_hat

rmse = np.sqrt(mean_squared_error(y_true, y_pred))
print(f"Root Mean Squared Error: {rmse}")

r2 = r2_score(y_true, y_pred)
print(f"R-squared: {r2}")

Root Mean Squared Error: 2.79638515090793
R-squared: 0.9557405708659336


In [12]:
# Save the trained model

model.save('AAPL8000.keras')

In [13]:
# loading saved model from folder

from tensorflow.keras.models import load_model

# Load the saved model
l_model = load_model('AAPL8000.keras')

In [14]:
# testing extraction of saved model

l_model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step


array([[181.18526],
       [176.46631],
       [171.78508],
       [173.33928],
       [188.5122 ],
       [187.3178 ],
       [180.4062 ],
       [176.39352],
       [152.99919],
       [147.2484 ],
       [153.84889]], dtype=float32)